CREATE TABLE IF NOT EXISTS CLIENTE
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(255),
    APELLIDO VARCHAR(255),
    EMAIL VARCHAR(255),
    FECHA_DE_NACIMIENTO TIMESTAMP(6)
);

ALTER TABLE CLIENTE
	ADD CONSTRAINT UK_EMAIL UNIQUE (EMAIL);

CREATE TABLE IF NOT EXISTS VENTA
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ID_CLIENTE BIGINT,
    FECHA TIMESTAMP(6)
);

ALTER TABLE VENTA
    ADD CONSTRAINT FK_VENTA_CLIENTE
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTE (ID);

CREATE TABLE IF NOT EXISTS PRODUCTO
  (
      ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
      NOMBRE VARCHAR(255),
      STOCK INT,
      PRECIO NUMERIC(11,2)
  );

  CREATE TABLE IF NOT EXISTS PRODUCTOVENTA
  (
      ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
      ID_PRODUCTO BIGINT,
      ID_VENTA BIGINT,
      CANTIDAD_COMPRADA INT,
      PRECIO_UNITARIO NUMERIC(11,2)
  );

ALTER TABLE PRODUCTOVENTA
    ADD CONSTRAINT FK_PRODUCTOVENTA_PRODUCTO
    FOREIGN KEY (ID_PRODUCTO)
    REFERENCES PRODUCTO (ID);

ALTER TABLE PRODUCTOVENTA
    ADD CONSTRAINT FK_PRODUCTOVENTA_VENTA
    FOREIGN KEY (ID_VENTA)
    REFERENCES VENTA(ID);